site_name: mopack
docs_dir: doc
repo_url: https://github.com/jimporter/mopack/
edit_uri: ""
copyright: Copyright &copy; 2020-2023 Jim Porter

theme:
  name: yeti-classic
  hljs_languages: [yaml]
extra_css:
  - css/extra.css
  - css/version-select.css
extra_javascript:
  - js/version-select.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: ยง

nav:
  - Home: index.md
  - User Guide:
    - Resolving Packages With mopack: user/resolving.md
    - Writing mopack.yml Configurations: user/writing.md
  - Reference:
    - File Structure: reference/file-structure.md
    - Packages: reference/packages.md
    - Builders: reference/builders.md
    - Linkage: reference/linkage.md
    - Expressions: reference/expressions.md
    - Command-Line Interface: reference/command-line.md
    - Environment Variables: reference/environment-vars.md
  - About:
    - Changes: about/changes.md
    - License: about/license.md
