from . import *


class HelpTest(SubprocessTestCase):
    def test_help(self):
        output = self.assertPopen(mopack_cmd('help'))
        self.assertRegex(output, r'^usage: mopack \[-h\] \[--version\]')

    def test_help_subcommand(self):
        output = self.assertPopen(mopack_cmd('help', 'resolve'))
        self.assertRegex(output, r'^usage: mopack resolve \[-h\]')

    def test_help_subcommand_extra(self):
        output = self.assertPopen(mopack_cmd('help', 'resolve', 'mopack.yml'))
        self.assertRegex(output, r'^usage: mopack resolve \[-h\]')


class GenerateCompletionTest(SubprocessTestCase):
    def test_completion(self):
        output = self.assertPopen(mopack_cmd('generate-completion', '-sbash'))
        self.assertRegex(output, r'(?m)^# AUTOMATICALLY GENERATED by `shtab`')
